output_dir: ~/scratch/protein_output

dataset:
  class: EnzymeCommission
  path: ~/scratch/protein-datasets/
  test_cutoff: 0.95
  atom_feature: null
  bond_feature: null
  transform:
    class: ProteinView
    view: residue

task:
  class: MultipleBinaryClassification
  model:
    class: ProteinLSTM
    input_dim: 21
    hidden_dim: 640
    num_layers: 3
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 2

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: {{ gpus }}
  batch_size: 8
  log_interval: 1000

metric: f1_max

train:
  num_epoch: 200
